services:
  # Spring Boot Application
  malicious-url-detector:
    build:
      context: .
      dockerfile: src/main/resources/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ML_MICROSERVICE_URL=http://python-ml-microservice:5002
      - SIMPLE_ML_MICROSERVICE_URL=http://simple-ml-microservice:5001
    depends_on:
      python-ml-microservice:
        condition: service_healthy
      simple-ml-microservice:
        condition: service_healthy
    networks:
      - malware-detector-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Advanced Python ML Microservice (with HuggingFace models)
  python-ml-microservice:
    build:
      context: ./python_microservice
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - HF_MODEL_NAME=distilbert-base-uncased
      - PYTHONUNBUFFERED=1
    networks:
      - malware-detector-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.75'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Simple ML Microservice (basic Flask app)
  simple-ml-microservice:
    build:
      context: ./ml_microservice
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - PYTHONUNBUFFERED=1
    networks:
      - malware-detector-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

networks:
  malware-detector-network:
    driver: bridge 