server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:h2:mem:urlscanner
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

# External ML API configuration
ml:
  api:
    enabled: true
    # We'll use HuggingFace Inference API instead of local microservices
    huggingface:
      enabled: true
      api-url: https://api-inference.huggingface.co/models
      model-name: microsoft/DialoGPT-medium

# Logging configuration for Render
logging:
  level:
    com.example.malwaredetector: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized 