# Render-specific Spring Boot configuration
# This file is loaded when SPRING_PROFILES_ACTIVE=render

server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:h2:mem:urlscanner
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: false  # Disable H2 console for faster startup
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false  # Disable OSIV for better performance

# External ML API configuration
ml:
  api:
    enabled: true
    huggingface:
      enabled: true
      api-url: https://api-inference.huggingface.co/models
      model-name: microsoft/DialoGPT-medium
  # Disable local ML microservice for Render
  microservice:
    enabled: false
    url: http://localhost:5002
    timeout: 5

# Disable heavy services for Render
services:
  dynamic-content-analyzer:
    enabled: false
  virus-total:
    enabled: false
  google-safe-browsing:
    enabled: false
  phish-tank:
    enabled: false

# Logging configuration for Render
logging:
  level:
    com.example.malwaredetector: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
    org.springframework.boot.autoconfigure: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints for health checks - simplified
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  health:
    defaults:
      enabled: true

# Optimize startup time
spring.main.lazy-initialization: true 