services:
  - type: web
    name: ml-microservice
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5001
      - key: HF_MODEL_NAME
        value: distilbert-base-uncased
    autoDeploy: true 