services:
  - type: web
    name: python-ml-microservice
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python ml_microservice.py
    envVars:
      - key: PORT
        value: 5002
      - key: HF_MODEL_NAME
        value: distilbert-base-uncased
    autoDeploy: true 