# Render-specific Spring Boot configuration
# This file is loaded when SPRING_PROFILES_ACTIVE=render

server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:h2:mem:urlscanner
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: false  # Disable H2 console for faster startup
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false  # Disable OSIV for better performance
  main:
    lazy-initialization: true  # Defer bean creation for faster startup
  logging:
    level:
      com.example.malwaredetector: INFO
      org.springframework.web: WARN
      org.hibernate: WARN

# External ML API configuration
ml:
  api:
    enabled: true
    huggingface:
      enabled: true
      api-url: https://api-inference.huggingface.co/models
      model-name: microsoft/DialoGPT-medium
      api-key: ${HUGGINGFACE_API_KEY:}  # Optional API key
  # Deployed microservices on Render
  microservice:
    enabled: true
    url: ${ML_MICROSERVICE_URL:https://python-ml-microservice.onrender.com}
    timeout: 10000
  python-microservice:
    enabled: true
    url: ${PYTHON_MICROSERVICE_URL:https://python-app-microservice.onrender.com}
    timeout: 10000
  ml-microservice:
    enabled: true
    url: ${ML_MICROSERVICE_3_URL:https://ml-microservice.onrender.com}
    timeout: 10000

# Disable heavy services that require API keys
virus-total:
  enabled: false
  api-key: ${VIRUSTOTAL_API_KEY:}

google-safe-browsing:
  enabled: false
  api-key: ${GOOGLE_SAFEBROWSING_API_KEY:}

phish-tank:
  enabled: false

# Actuator configuration for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always 